#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS            #
#                                                                    #
#                Author: HOSTVN Technical Team                       #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function
source /var/hostvn/menu/helpers/menu
source /var/hostvn/menu/helpers/variable_common

CHOICE=1

printf "%s========================+%s\n" "${GREEN}" "${NC}"
printf "%s    SSL Manager         %s\n" "${GREEN}" "${NC}"
printf "%s========================+%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]; do
    printf "%s1. Cai dat Let's Encrypt SSL%s\n" "${GREEN}" "${NC}"
    printf "%s2. SSL cho Alias domain%s\n" "${GREEN}" "${NC}"
    printf "%s3. Go bo Let's Encrypt SSL%s\n" "${GREEN}" "${NC}"
    printf "%s4. CloudFlare DNS API%s\n" "${GREEN}" "${NC}"
    printf "%s========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]; then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
    1)
        clear
        bash "${BASH_DIR}"/menu/controller/ssl/create_le_ssl
        ;;
    2)
        clear
        bash "${BASH_DIR}"/menu/controller/ssl/le_alias_domain
        ;;
    3)
        clear
        bash "${BASH_DIR}"/menu/controller/ssl/remove_le
        ;;
    4)
        clear
        bash "${BASH_DIR}"/menu/controller/ssl/cf_api
        ;;
    0)
        clear
        menu_primary
        ;;
    *)
        clear
        printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}"
        ;;
    esac
done